### ISSUE TITLE
Get rid of legacy "Type: [Folder]" hint

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capella-rm-bridge#13]
The RM Bridge currently supports two ways of distinguishing whether an "item" is a RequirementsFolder or a Requirement. The first one is through the presence or absence of the `children` key, which is – as far as I'm aware – the recommended way (where presence of the key, even if it contains an empty list, means it's a folder). The second way is to declare the special attribute "Type" to have the value "[Folder]" (notice the casing and brackets).

The latter is a left-over from one specific importer, which had (or still has?) a bug that made it not produce empty children lists for folders. This behavior should be deprecated and eventually removed, so that presence/absence of the "children" key is the only discriminator. ("There should be one-- and preferably only one --obvious way to do it.")

**Comment by ewuerger** [comment]
This was done in #23.
